server:
  port: 6789
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: stlang
#  30 day: 30 * 24 * 60 * 60 (s)